[package]
name = "pip-executor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
pip-contracts = { path = "../pip-contracts" }
pip-core = { path = "../pip-core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
wait-timeout.workspace = true
tempfile.workspace = true
