[package]
name = "pip-control"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
base64.workspace = true
axum.workspace = true
ed25519-dalek.workspace = true
pip-contracts = { path = "../pip-contracts" }
pip-controller = { path = "../pip-controller" }
pip-core = { path = "../pip-core" }
pip-executor = { path = "../pip-executor" }
pip-github = { path = "../pip-github" }
pip-hermes = { path = "../pip-hermes" }
pip-store = { path = "../pip-store" }
serde.workspace = true
serde_json.workspace = true
rustix.workspace = true
sha2.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true

[dev-dependencies]
hmac.workspace = true
tempfile.workspace = true

[[bin]]
name = "pip-control"
path = "src/main.rs"
