[package]
name = "pip-controller"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
pip-contracts = { path = "../pip-contracts" }
pip-core = { path = "../pip-core" }
pip-hermes = { path = "../pip-hermes" }
pip-store = { path = "../pip-store" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
